True
is_hungry = False
print(type(is_cool))
print(is_cool)
print(is_hungry)
print(not is_hungry)
print(not is_cool)
print(is_cool and is_hungry)
print(is_cool or is_hungry)
print(is_cool and not is_hungry)
print(is_cool or not is_hungry)
print(is_hungry or not is_cool)
print(is_hungry and not is_cool)
print(is_hungry or not is_hungry)
print(is_hungry and not is_hungry)
print(is_cool or not is_cool)
print(is_cool and not is_cool)
print(is_cool and is_cool)
print(is_hungry or is_hungry)
print(is_cool or is_hungry)
print(is_cool and is_hungry)